version: '3.9'

x-django: &django
  build:
    context: .
    target: app-with-static
  env_file: .env
  environment:
    ENVIRONMENT: staging
    DEBUG: "false"
    DATABASE_URL: postgres://{{ cookiecutter.project_slug }}:${DB_PASSWORD:-django}@db/{{ cookiecutter.project_slug }}
    CACHE_URL: rediscache://redis
    VIRTUAL_HOST: default
    VIRTUAL_PORT: 8000
    VIRTUAL_PATH: /
    MEDIA_URL: /media/
  volumes:
    - django-media:/app/media
  depends_on:
    - db
    - redis

services:
  django:
    << : *django

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: "{{ cookiecutter.project_slug }}"
      POSTGRES_USER: "{{ cookiecutter.project_slug }}"
      POSTGRES_PASSWORD: ${DB_PASSWORD:-django}
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./initdb.d:/docker-entrypoint-initdb.d

  redis:
    image: redis:alpine

  uploads:
    image: flashspys/nginx-static
    restart: always
    environment:
      VIRTUAL_HOST: default
      VIRTUAL_PORT: 80
      VIRTUAL_PATH: /media
      VIRTUAL_DEST: /
    volumes:
      - django-media:/static

  web:
    image: nginxproxy/nginx-proxy:alpine
    restart: always
    ports:
      - ${HTTP_PORT:-80}:80
    environment:
      DEFAULT_HOST: default
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro


volumes:
  db-data:
  django-media:
