version: '3.9'

x-django: &django
  build:
    context: .
    target: app{% if cookiecutter.whitenoise_static %}-with-static{% endif %}
  env_file: .env
  environment:
    ENVIRONMENT: staging
    DEBUG: "false"
    DATABASE_URL: postgres://{{ cookiecutter.project_slug }}:${DB_PASSWORD:-django}@db/{{ cookiecutter.project_slug }}
    CACHE_URL: rediscache://redis
    MEDIA_URL: /files/media/
    STATIC_URL: {% if not cookiecutter.whitenoise_static %}/files{% endif %}/static/
    VIRTUAL_PORT: 8000
    VIRTUAL_PATH: /
  volumes:
    - django-media:/app/media
{% if not cookiecutter.whitenoise_static %}    - django-static:/app/staticfiles{% endif %}
  depends_on:
    - db
    - redis

services:
  django:
    << : *django

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: {{ cookiecutter.project_slug }}
      POSTGRES_USER: {{ cookiecutter.project_slug }}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-django}
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./initdb.d:/docker-entrypoint-initdb.d

  redis:
    image: redis:alpine

  files:
    image: flashspys/nginx-static
    restart: always
    environment:
      VIRTUAL_PORT: 80
      VIRTUAL_PATH: /files
      VIRTUAL_DEST: /
    env_file: .env
    volumes:
      - django-media:/static/media
{% if not cookiecutter.whitenoise_static %}      - django-static:/static/static{% endif %}

  web:
    image: nginxproxy/nginx-proxy:alpine
    restart: always
    ports:
      - ${HTTP_PORT:-80}:80
    environment:
      DEFAULT_HOST: localhost
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro


volumes:
  db-data:
  django-static:
  django-media:
